base_url: /
future: false
lsi: false
permalink: /blog/:year/:month/:day/:title
paginate: 1
url: http://dirtyinformation.com
markdown: kramdown
name: Dirty Information
description: Raw ramblings about software development
highlighter: rouge
